### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by JamieSlome** [VastRock-Huang/miniVPN#1]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@ihsinme) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by peakcrosser7** [comment]
Thanks for your suggestion!  
I have added a `SECURITY.md`, and you can send a message to vastrockhuang162@gmail.com. Thanks!
